version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd frontend/app && yarn start"
    ports:
      - "3000:3000"
    tty:
      true